Student information intial look
## import libraries
# load the data

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data/RTT_36_data.csv')

In [3]:
rows, cols = df.shape

In [4]:
df.head()
df.tail()

,ID,Start time,Completion time,Email,Name,Last modified time,What is your cohort number?,What month did your cohort start?,What year is it?,What is your age?,...,What streaming services do you subscribe to?,"Are you a dog person, cat person, both, or neither?",Does pineapple belong on pizza?,What is your favorite color?,What destination would you choose?,Favorite board / card game?,Favorite video game?,Favorite movie?,Favorite TV show?,What is your favorite sport to watch or play?
24,25,8/4/26 11:47:52,8/4/26 12:17:23,anonymous,NaN,NaN,2026-RT-36,August,2026,44,...,"None, I'm not subscribed to any of those strea...",Both,2.0,Black,Big City,"Spades, UNO",Madden Football and Soul Caliber,"Stomp The yard, You Got Served, Saw","America's Best Dance Crew, So You Think You Ca...",Football and Basketball
25,26,8/4/26 11:48:02,8/4/26 12:38:12,anonymous,NaN,NaN,2026-RTT-36,August,2026,63,...,Amazon Prime;,Both,5.0,Orange,Mountains,Solitaire,NaN,Fifth-Element,Reacher,Snowboarding
26,27,8/4/26 11:47:50,8/4/26 12:50:19,anonymous,NaN,NaN,2026-rtt-36,August,2026,32,...,Netflix;Prime;,Neither,3.0,Blue,National Park,Non,Non,Empire Waist,Arrested Development,Soccer
27,28,8/4/26 12:58:33,8/4/26 13:01:35,anonymous,NaN,NaN,RTT-36,August,2026,19,...,None;,Cat,4.0,Blue,Mountains,Monopoly,COD mobile,Scooby Doo,Henry Danger,Running
28,29,8/4/26 13:07:43,8/4/26 13:14:10,anonymous,NaN,NaN,2026-RTT-36,August,2026,34,...,NaN,Dog,5.0,Green,Beach,Sorry,Bomberman Hero,A Walk to Remember,NaN,"Basketball, Flag Football"

In [5]:
df.describe()

,ID,Name,Last modified time,What year is it?,What is your age?,How many siblings do you have?,How comfortable are you learning new technology?,Does pineapple belong on pizza?
count,29.000000,0.0,0.0,29.0,29.000000,29.000000,29.000000,28.000000
mean,15.000000,NaN,NaN,2026.0,37.172414,2.655172,4.655172,3.357143
std,8.514693,NaN,NaN,0.0,8.705782,2.635958,0.613879,1.704336
min,1.000000,NaN,NaN,2026.0,19.000000,0.000000,3.000000,1.000000
25%,8.000000,NaN,NaN,2026.0,32.000000,1.000000,4.000000,1.750000
50%,15.000000,NaN,NaN,2026.0,38.000000,2.000000,5.000000,4.000000
75%,22.000000,NaN,NaN,2026.0,41.000000,4.000000,5.000000,5.000000
max,29.000000,NaN,NaN,2026.0,63.000000,12.000000,5.000000,5.000000

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 55 columns):
 #   Column                                                                          Non-Null Count  Dtype
---  ------                                                                          --------------  -----
 0   ID                                                                              29 non-null     int64
 1   Start time                                                                      29 non-null     str
 2   Completion time                                                                 29 non-null     str
 3   Email                                                                           29 non-null     str
 4   Name                                                                            0 non-null      float64
 5   Last modified time                                                              0 non-null      float64
 6   What is your cohort number?                                                     29 non-null     str
 7   What month did your cohort start?                                               29 non-null     str
 8   What year is it?                                                                29 non-null     int64
 9   What is your age?                                                               29 non-null     int64
 10  What is your gender?                                                            29 non-null     str
 11  What's you dominant hand?                                                       29 non-null     str
 12  Do you prefer sweet or salty snacks?                                            29 non-null     str
 13  How many siblings do you have?                                                  29 non-null     int64
 14  What state do you live in?                                                      29 non-null     str
 15  What time zone are you in?                                                      29 non-null     str
 16  What language do you speak most often at home?                                  29 non-null     str
 17  What other languages can you speak or understand?                               25 non-null     str
 18  What month were you born?                                                       29 non-null     str
 19  Do you prefer calling or texting?                                               29 non-null     str
 20  What season do you enjoy the most?                                              29 non-null     str
 21  What best describes you?                                                        29 non-null     str
 22  How many people live in your household (including you?                          29 non-null     str
 23  How many pets do you have?                                                      28 non-null     str
 24  How many hours of sleep do you usually get each night?                          29 non-null     str
 25  Which best describes you right now?                                             29 non-null     str
 26  What industry do you currently work in (or most recently worked in)?
           29 non-null     str
 27  How many years have you worked?                                                 29 non-null     str
 28  How many hours each week do you plan to study for this course?                  29 non-null     str
 29  Have you ever taken an online course before?                                    29 non-null     str
 30  What OS are you using?                                                          29 non-null     str
 31  Which browser do you use the most?                                              29 non-null     str
 32  How comfortable are you learning new technology?                                29 non-null     int64
 33  About how many hours per day do you spend using a computer?                     29 non-null     str
 34  About how many hours a day do you spend on your phone?                          29 non-null     str
 35  What AI tools have you used?                                                    29 non-null     str
 36  Have you ever written computer code before (python, sql, c, JS, Java, ect...)?  29 non-null     str
 37  Which social media platforms do you use regularly?                              29 non-null     str
 38  What hobbies do you enjoy?                                                      29 non-null     str
 39  How often do you exercise?                                                      29 non-null     str
 40  Do you enjoy cooking?                                                           28 non-null     str
 41  Coffee, tea, both, neither?                                                     28 non-null     str
 42  Approximately how many books did you read last year?                            28 non-null     str
 43  Which music genres do you enjoy?                                                28 non-null     str
 44  Which movie or TV genres do you enjoy?                                          29 non-null     str
 45  What streaming services do you subscribe to?                                    27 non-null     str
 46  Are you a dog person, cat person, both, or neither?                             29 non-null     str
 47  Does pineapple belong on pizza?                                                 28 non-null     float64
 48  What is your favorite color?                                                    29 non-null     str
 49  What destination would you choose?                                              29 non-null     str
 50  Favorite board / card game?                                                     27 non-null     str
 51  Favorite video game?                                                            24 non-null     str
 52  Favorite movie?                                                                 28 non-null     str
 53  Favorite TV show?                                                               25 non-null     str
 54  What is your favorite sport to watch or play?                                   28 non-null     str
dtypes: float64(3), int64(5), str(47)
memory usage: 12.6 KB